from nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

LABEL author="Stanford Surreal team"

RUN mkdir /mylibs
WORKDIR /mylibs

# RUN apt-get update
# RUN apt-get install -y expect
# COPY keyboard_configuration.exp .
# RUN expect keyboard_configuration.exp
RUN apt-get update && apt-get -y install cmake unzip bzip2 curl git wget libglfw3 libglew1.13 libglib2.0-0 libsm6 xorg-dev

RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
	&& bash Miniconda3-latest-Linux-x86_64.sh -p /mylibs/miniconda -b
RUN rm /mylibs/Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/mylibs/miniconda/bin:${PATH}

# mujoco
RUN mkdir /root/.mujoco
WORKDIR /root/.mujoco
RUN wget https://www.roboti.us/download/mjpro150_linux.zip \
    && unzip mjpro150_linux.zip \
    && rm mjpro150_linux.zip
RUN wget https://www.roboti.us/download/mjpro131_linux.zip \
    && unzip mjpro131_linux.zip \
    && rm mjpro131_linux.zip

# pytorch
# [anaconda root directory]
WORKDIR /mylibs
RUN conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
RUN conda install -c pytorch magma-cuda90
RUN git clone --recursive https://github.com/pytorch/pytorch
ENV CMAKE_PREFIX_PATH=/mylibs/miniconda/bin/
WORKDIR /mylibs/pytorch
RUN git submodule update --init
RUN TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    pip install -v .
WORKDIR /mylibs
RUN git clone https://github.com/pytorch/vision.git && cd vision && pip install -v .

COPY requirements.txt /mylibs/
RUN pip install -r /mylibs/requirements.txt

# required for imageio
# RUN conda install --yes ffmpeg -c conda-forge

# DM control suite
RUN pip install git+git://github.com/deepmind/dm_control.git

ENV DISABLE_MUJOCO_RENDERING=1

WORKDIR /root
COPY entry.py /mylibs
RUN chmod +x /mylibs/entry.py
ENTRYPOINT ["/mylibs/entry.py"]

