FROM ubuntu:16.04

LABEL author="Stanford Surreal team"

RUN mkdir /mylibs
WORKDIR /mylibs

# RUN apt-get update
# RUN apt-get install -y expect
# COPY keyboard_configuration.exp .
# RUN expect keyboard_configuration.exp
# RUN yes | apt-get -y install xserver-xorg-video-dummy cmake libglfw3 xorg-dev unzip bzip2 curl git libglew1.13 wget
RUN apt-get update && apt-get -y install xserver-xorg-video-dummy cmake libglfw3 xorg-dev unzip bzip2 curl git libglew1.13 wget

RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
	&& bash Miniconda3-latest-Linux-x86_64.sh -p /mylibs/miniconda -b
RUN rm /mylibs/Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/mylibs/miniconda/bin:${PATH}

RUN apt-get -y remove libglfw3 \
	&& git clone https://github.com/glfw/glfw.git
WORKDIR /mylibs/glfw
RUN cmake -DBUILD_SHARED_LIBS=ON . \
	&& make \
	&& make install
WORKDIR /
RUN rm -r /mylibs/glfw

# mujoco
RUN mkdir /root/.mujoco
WORKDIR /root/.mujoco
RUN wget https://www.roboti.us/download/mjpro150_linux.zip \
    && unzip mjpro150_linux.zip \
    && rm mjpro150_linux.zip
RUN wget https://www.roboti.us/download/mjpro131_linux.zip \
    && unzip mjpro131_linux.zip \
    && rm mjpro131_linux.zip

# pytorch
RUN conda install --yes pytorch-cpu torchvision -c pytorch
COPY requirements.txt /mylibs/
RUN pip install -r /mylibs/requirements.txt

# required for imageio
RUN conda install -y ffmpeg -c conda-forge

# DM control suite
RUN pip install git+git://github.com/deepmind/dm_control.git

# fake display to work around the GLFW problem
RUN mkdir /etc/fakeX \
	&& touch /etc/fakeX/10.log
COPY xorg.conf /etc/fakeX/
COPY xorg.service /etc/systemd/system/
RUN systemctl enable xorg

ENV DISPLAY=:10

WORKDIR /root
COPY entry.py /mylibs
RUN chmod +x /mylibs/entry.py
ENTRYPOINT ["/mylibs/entry.py"]

RUN apt-get update && apt-get install -y libgl1-mesa-dev libgl1-mesa-glx libosmesa6-dev