from nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

LABEL author="Stanford Surreal team"

RUN mkdir /mylibs
WORKDIR /mylibs

# RUN apt-get update
# RUN apt-get install -y expect
# COPY keyboard_configuration.exp .
# RUN expect keyboard_configuration.exp
RUN apt-get update && apt-get -y install cmake unzip bzip2 curl git wget libglfw3 libglew1.13 libglib2.0-0 libsm6 xorg-dev

RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
	&& bash Miniconda3-latest-Linux-x86_64.sh -p /mylibs/miniconda -b
RUN rm /mylibs/Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/mylibs/miniconda/bin:${PATH}

# mujoco
RUN mkdir /root/.mujoco
WORKDIR /root/.mujoco
RUN wget https://www.roboti.us/download/mjpro150_linux.zip \
    && unzip mjpro150_linux.zip \
    && rm mjpro150_linux.zip
RUN wget https://www.roboti.us/download/mjpro131_linux.zip \
    && unzip mjpro131_linux.zip \
    && rm mjpro131_linux.zip

# pytorch
RUN conda install --yes pytorch  torchvision -c pytorch
COPY requirements.txt /mylibs/
RUN pip install -r /mylibs/requirements.txt

# required for imageio
# RUN conda install -y ffmpeg -c conda-forge

# DM control suite
RUN pip install git+git://github.com/deepmind/dm_control.git

ENV DISABLE_MUJOCO_RENDERING=1

WORKDIR /root
COPY entry.py /mylibs
RUN chmod +x /mylibs/entry.py
ENTRYPOINT ["/mylibs/entry.py"]

RUN apt-get update && apt-get install -y libglu1-mesa-dev libglew-dev libgl1-mesa-dev libgl1-mesa-glx libglew-dev libosmesa6-dev
RUN pip install -U mujoco_py~=1.50
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/root/.mujoco/mjpro150/bin
RUN apt-get update && apt-get install -y patchelf