FROM us.gcr.io/surreal-dev-188523/surreal-base-cpu:latest

# fake display to work around the GLFW problem
RUN mkdir /etc/fakeX \
	&& touch /etc/fakeX/10.log
COPY xorg.conf /etc/fakeX/
COPY xorg.service /etc/systemd/system/
RUN systemctl enable xorg

ENV DISPLAY=:10

ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/root/.mujoco/mjpro150/bin
RUN apt-get update && apt-get install -y patchelf

WORKDIR /root
COPY entry.py /mylibs
RUN chmod +x /mylibs/entry.py
ENTRYPOINT ["/mylibs/entry.py"]

RUN pip install pygame gym[atari]