#!/usr/bin/env expect
# skip annoying interactive questions during `apt-get update`
# https://www.hiroom2.com/2017/02/24/docker-using-expect-script-directly-in-dockerfile-will-be-complicated

set timeout -1
spawn apt-get install -y keyboard-configuration
expect {
    "\\\[More\\\]" { send "\n"; exp_continue; }
    "Country of origin for the keyboard: " { send "29\n"; }
}
expect {
    "\\\[More\\\]" { send "\n"; exp_continue; }
    "Keyboard layout: " { send "1\n" }
}
expect eof